version: '3.7'

services:
  #MySQL Database
  mysql-database:
    container_name: mysql-aluraflix
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: aluraflix
      MYSQL_ROOT_PASSWORD: 12345
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
